spring:
  datasource:
    username: root
    password: 163512
    url: jdbc:mysql://localhost:3306/test?serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 80
  servlet:
    context-path: /WX
